#Importacion de archivo con las clases a usar.
import EvaluaciónUnidad4 as E

#Instanciacion de objetos.
Camila = E.Persona('Camila','Morales', 30, 1.62, 'Preparatoria', 2263850139)
Diego = E.Persona('Diego', 'Méndez', 18, 1.60, 'Preparatoria', 2311322030)
Veronica = E.Administrador('Veronica','Gamino', 39, 1.48, 'Licenciatura', 2311013784, 'M&M Company', 3000)
Juan = E.Contador('Juan','Reyes',43,1.65,'Licenciatura',2311297057, 'M&M Company', 4000)
Manuel = E.JefeDeMarketing('Manuel','Torres',25,1.88,'Licenciatura',2314782905,'M&M Company',2800)
Cristhian = E.Gerente('Cristhian', 'Morales', 21,1.68, 'Licenciatura',2261111837,'M&M Company',6000)

print('\n--Clase persona--')
Diego.Presentarce()
Diego.Vestir('Pantalon negro','Playera Blanca','Gafas')
Diego.Comer('Hamburguesa','Jugo de naranja')
Diego.AccionAleatoria()
Diego.Dormir(6)

Camila.Presentarce()
Camila.Vestir('Vestido Rojo', 'Saco negro', 'Chalina')
Camila.Comer('Coctel de frutas','Frappe')
Camila.AccionAleatoria()
Camila.Dormir(9)

print('\n--Clase Administrador--')
Veronica.Presentarce()
Veronica.Vestir('Jean gris', 'Sueter', 'Collar')
Veronica.Curriculum()
Veronica.TrabajoAleatorio()
Veronica.Dormir(7)

print('\n--Clase Contador--')
Juan.Presentarce()
Juan.Vestir('Pantalon azul','Cardigan gris','Reloj plateado')
Juan.Curriculum()
Juan.TrabajoAleatorio()
Juan.Dormir(6)

print('\n--Clase Jefe de Marketing--')
Manuel.Presentarce()
Manuel.Vestir('Pantalon Cafe','Abrigo gris','Pulsera')
Manuel.Curriculum()
Manuel.TrabajoAleatorio()
Manuel.Dormir(10)

print('\n--Clase Gerente--')
Cristhian.Presentarce()
Cristhian.Vestir('Traje negro','Camisa Blanca','Corbata')
Cristhian.Curriculum()
Cristhian.TrabajoAleatorio()
Cristhian.Entrevistar(Cristhian,Diego)
Cristhian.Contratar(Cristhian,Diego)
Cristhian.Entrevistar(Cristhian,Camila)
Cristhian.Contratar(Cristhian, Camila)
Cristhian.Dormir(8)
